services:
  - type: web
    name: rideshare-backend
    runtime: docker
    rootDir: .
    dockerfilePath: ./rideshare-app/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 90d 
